<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-AQ50KAH1" name="cn.test.framework.tests.InterfaceTest" tests="1" failures="0" timestamp="12 Apr 2018 08:31:56 GMT" time="0.007" errors="1">
  <testcase name="test" time="0.007" classname="cn.test.framework.tests.InterfaceTest">
    <error type="java.lang.Throwable">
      <![CDATA[java.lang.Throwable
	at message : expected [2] but found [4] in method : .test(InterfaceTest:99)
	at cn.test.framework.tests.InterfaceTest.test(InterfaceTest.java:99)
	at message : expected [3] but found [2] in method : .test(InterfaceTest:99)
	at cn.test.framework.tests.InterfaceTest.test(InterfaceTest.java:99)
	at message : expected [1] but found [3] in method : .test(InterfaceTest:99)
	at cn.test.framework.tests.InterfaceTest.test(InterfaceTest.java:99)
	at message : expected [1] but found [0] in method : .test(InterfaceTest:99)
	at cn.test.framework.tests.InterfaceTest.test(InterfaceTest.java:99)
	at message : expected [2] but found [1] in method : .test(InterfaceTest:99)
	at cn.test.framework.tests.InterfaceTest.test(InterfaceTest.java:99)
	at message : expected [4] but found [0] in method : .test(InterfaceTest:99)
	at cn.test.framework.tests.InterfaceTest.test(InterfaceTest.java:99)
	at message : expected [4] but found [1] in method : .test(InterfaceTest:99)
	at cn.test.framework.tests.InterfaceTest.test(InterfaceTest.java:99)
	at message : expected [0] but found [1] in method : .test(InterfaceTest:99)
	at cn.test.framework.tests.InterfaceTest.test(InterfaceTest.java:99)
]]>
    </error>
  </testcase> <!-- test -->
</testsuite> <!-- cn.test.framework.tests.InterfaceTest -->
